Data_Quality/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from dqc import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^dqc/', include('dqc.urls'))
]

dqc/urls.py
#!/usr/bin/env python
# -*-coding:utf-8-*-
from django.conf.urls import url
from . import views

app_name = "dqc"
urlpatterns = [
	url(r'^$', views.dqc_login, name='login'),
	url(r'^del_rule$', views.dqc_del, name='del'),
	url(r'^add_rule$', views.dqc_add, name='add'),
	url(r'^edit_rule$', views.dqc_edit, name='edit'),
	url(r'^search$', views.dqc_search, name='search'),
	url(r'^index$', views.index, name='index'),
]

dqc/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Alarmconf(models.Model):
	app_name = models.CharField(max_length=50)
	job_name = models.CharField(max_length=100)
	db_name = models.CharField(max_length=20)
	table_name = models.CharField(max_length=50)
	file_dir = models.CharField(max_length=50)
	static_column = models.CharField(max_length=100)
	error_alarm = models.CharField(max_length=10)
	date_week = models.CharField(max_length=100)
	date_alarm = models.CharField(max_length=10)
	owner = models.CharField(max_length=50)
	mobile = models.CharField(max_length=50)
	valid_flag = models.CharField(max_length=50)

class UserInfo(models.Model):
	user_name = models.CharField(max_length=20,unique=True)
	user_pass = models.CharField(max_length=20)
	is_admin = models.BigIntegerField()
	create_time = models.DateTimeField(auto_now_add=True)
	update_time = models.DateTimeField(auto_now=True)

dqc/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from .models import Alarmconf,UserInfo
from django.shortcuts import redirect
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from django.db.models import Q

# Create your views here.




def index(request):
	dqc_list = Alarmconf.objects.all()

	pn = Paginator(list(dqc_list), 12)
	page = request.GET.get('page', 1)
	cur_page = int(page)

	try:
		print(page)
		dqc_list = pn.page(page)
	except PageNotAnInteger:
		dqc_list = pn.page(1)
	except EmptyPage:
		dqc_list = pn.page(pn.num_pages)
	context = {
		"dqc_list": dqc_list
	}
	"""locals()返回的字典对所有局部变量的名称与值进行映射"""
	return render(request, "index.html", context)

def dqc_login(request):
	if request.method == "GET":
		return render(request,"login.html")
	elif request.method == "POST":
		username = request.POST.get("username")
		password = request.POST.get("password")
		if request.POST.has_key("login"):
			res = UserInfo.objects.filter(user_name=username,user_pass=password).count()
			if res == 1:
				return redirect("dqc:index")
			else:
				content = {
					"login_check":"login failed!!!"
				}
				return render(request,"login.html",content)
		else:
			res = UserInfo.objects.filter(user_name=username).count()
			if res == 1:
				content = {
					"login_check": "User already exists!!!"
				}
				return render(request, "login.html", content)
			else:
				UserInfo.objects.create(user_name=username, user_pass=password,is_admin=1)
				content = {
					"login_check": "register successful!!!"
				}
				return render(request, "login.html", content)



def dqc_del(request):
	nid = request.GET.get('nid')
	Alarmconf.objects.filter(id=nid).delete()
	return redirect('dqc:index')

def dqc_add(request):
	if request.method == "GET":
		return render(request, "add_rule.html")
	elif request.method == "POST":
		app_name = request.POST.get("app_name")
		job_name = request.POST.get("job_name")
		db_name = request.POST.get("db_name")
		table_name = request.POST.get("table_name")
		file_dir = request.POST.get("file_dir")
		static_column = request.POST.get("static_column")
		error_alarm = request.POST.get("error_alarm")
		date_week = request.POST.get("date_week")
		date_alarm = request.POST.get("date_alarm")
		owner = request.POST.get("owner")
		mobile = request.POST.get("mobile")
		valid_flag = request.POST.get("valid_flag")
		Alarmconf.objects.create(app_name = app_name,
								 job_name = job_name,
								 db_name = db_name,
								 table_name = table_name,
								 file_dir = file_dir,
								 static_column = static_column,
								 error_alarm = error_alarm,
								 date_week = date_week,
								 date_alarm = date_alarm,
								 owner = owner,
								 mobile = mobile,
								 valid_flag = valid_flag)
		return redirect('dqc:index')

def dqc_edit(request):
	if request.method == "GET":
		nid = request.GET.get('nid')
		query_set = Alarmconf.objects.filter(id=nid).first()
		context = {
			"dqc_list": query_set
		}
		return render(request, "edit_rule.html", context)
	elif request.method == "POST":
		nid = request.GET.get('nid')
		app_name = request.POST.get("app_name")
		job_name = request.POST.get("job_name")
		db_name = request.POST.get("db_name")
		table_name = request.POST.get("table_name")
		file_dir = request.POST.get("file_dir")
		static_column = request.POST.get("static_column")
		error_alarm = request.POST.get("error_alarm")
		date_week = request.POST.get("date_week")
		date_alarm = request.POST.get("date_alarm")
		owner = request.POST.get("owner")
		mobile = request.POST.get("mobile")
		valid_flag = request.POST.get("valid_flag")
		Alarmconf.objects.filter(id=nid).update(app_name = app_name,
												job_name = job_name,
												db_name = db_name,
												table_name = table_name,
												file_dir = file_dir,
												static_column = static_column,
												error_alarm = error_alarm,
												date_week = date_week,
												date_alarm = date_alarm,
												owner = owner,
												mobile = mobile,
												valid_flag = valid_flag)
		return redirect('dqc:index')


def dqc_search(request):
	text = request.GET.get('a')
	# print "text:{}".format(text)
	# print request.get_full_path()
	if text == None or text == "":
		dqc_list = Alarmconf.objects.all()
	else:
		"""多条件模糊匹配"""
		dqc_list = Alarmconf.objects.filter(Q(app_name__icontains=text)|Q(job_name__icontains=text)|Q(db_name__icontains=text)|Q(table_name__icontains=text)|Q(owner__icontains=text)|Q(mobile__icontains=text))

	pn = Paginator(dqc_list, 12)
	page = request.GET.get('page', 1)
	cur_page = int(page)

	try:
		print(page)
		dqc_list = pn.page(page)
	except PageNotAnInteger:
		dqc_list = pn.page(1)
	except EmptyPage:
		dqc_list = pn.page(pn.num_pages)
	"""这里要把搜索框的关键字传给前端,不然搜索翻页会有问题"""
	context = {
		"dqc_list": dqc_list,
		"param_input": text
	}
	"""locals()返回的字典对所有局部变量的名称与值进行映射"""
	return render(request, "index.html", context)

templates/add_rule.html
{% extends 'base.html' %}
{% block content %}

<div>

    <form action='{% url 'dqc:add' %}' method="POST">
    {% csrf_token %}
        <style>
        p { height:25px; line-height:25px;}
        input {type:"text";width:250px;height:25px;maxlength:"200"}
        </style>
        <div  style="width:200px; float:left;margin-left:100px">
            <p>应用名称：*</p>
            <p>作业名称：*</p>
            <p>库名：*</p>
            <p>表名：*</p>
            <p>文件路径：*</p>
            <p>统计字段名：*</p>
            <p>报错预警：*</p>
            <p>出数时间预警(星期)：*</p>
            <p>出数时间预警(小时)：*</p>
            <p>责任人：*</p>
            <p>责任人手机号：*</p>
            <p>有效标识：*</p>
        </div>
        <div class="form-group" style="width:500px; float:left">
            <p><input  name="app_name"  /></p>
            <p><input  name="job_name"  /></p>
            <p><input  name="db_name"  /></p>
            <p><input  name="table_name"  /></p>
            <p><input  name="file_dir"  /></p>
            <p><input  name="static_column"  /></p>
            <p><input  name="error_alarm"  /></p>
            <p><input  name="date_week"  /></p>
            <p><input  name="date_alarm" /></p>
            <p><input  name="owner"  /></p>
            <p><input  name="mobile" /></p>
            <p><input  name="valid_flag"  /></p>
            <p><input  type="submit" class="btn btn-info" style="width:60px;height:32px" value="保存" /></p>
        </div>

    </form>

</div>
{% endblock content %}

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>Data Management System</title>

    <!-- Bootstrap -->
      <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"/>
{#      <link href="{% static 'css/style.css' %}" rel="stylesheet"/>#}


    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <!-- Navigation -->
    <nav class="navbar navbar-default" >
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'dqc:index' %}">主页</a>
                <a class="navbar-brand" href="https://github.com/liaojinbo0723/Data_Quality">源码</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="my-nav">
          <ul class="nav navbar-nav navbar-right">
            <li><a class="glyphicon glyphicon-log-in" href="{% url 'dqc:index' %}">登录</a></li>
            <li><a class="glyphicon glyphicon-user" href="{% url 'dqc:index' %}">注册</a></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    <!-- Page Content -->
    {% block content %}{% endblock content %}

    <!-- jQuery -->
    <script src="{% static 'js/jquery-3.2.1.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>

templates/edit_rule.html
{% extends 'base.html' %}
{% block content %}
<div>


    <form action='{% url 'dqc:edit' %}?nid={{ dqc_list.id }}' method="POST">
    {% csrf_token %}
        <style>
        p { height:25px; line-height:25px;}
        input {type:"text";width:250px;height:25px;maxlength:"200"}
        </style>
        <div  style="width:200px; float:left;margin-left:100px">
            <p>应用名称：*</p>
            <p>作业名称：*</p>
            <p>库名：*</p>
            <p>表名：*</p>
            <p>文件路径：*</p>
            <p>统计字段名：*</p>
            <p>报错预警：*</p>
            <p>出数时间预警(星期)：*</p>
            <p>出数时间预警(小时)：*</p>
            <p>责任人：*</p>
            <p>责任人手机号：*</p>
            <p>有效标识：*</p>
        </div>
        <div  style="width:500px; float:left">
            <p><input  name="app_name"  value="{{ dqc_list.app_name }}" /></p>
            <p><input  name="job_name"  value="{{ dqc_list.job_name }}"/></p>
            <p><input  name="db_name"  value="{{ dqc_list.db_name }}"/></p>
            <p><input  name="table_name"  value="{{ dqc_list.table_name }}"/></p>
            <p><input  name="file_dir"  value="{{ dqc_list.file_dir }}"/></p>
            <p><input  name="static_column"  value="{{ dqc_list.static_column }}"/></p>
            <p><input  name="error_alarm"  value="{{ dqc_list.error_alarm }}"/></p>
            <p><input  name="date_week"  value="{{ dqc_list.date_week }}"/></p>
            <p><input  name="date_alarm"  value="{{ dqc_list.date_alarm }}"/></p>
            <p><input  name="owner"  value="{{ dqc_list.owner }}"/></p>
            <p><input  name="mobile"  value="{{ dqc_list.mobile }}"/></p>
            <p><input  name="valid_flag"  value="{{ dqc_list.valid_flag }}"/></p>
            <p><input type="submit" class="btn btn-info" style="width:60px;height:32px" value="保存" /></p>
        </div>
    </form>

</div>
{% endblock content %}

templates/index.html
{% extends 'base.html' %}
{% block content %}
<div>
    <div style="overflow: hidden;width: fit-content;margin: auto;">
        <form class="navbar-form navbar-left" action="{% url 'dqc:add' %}" method="get">
            {% csrf_token %}
            <div class="form-group" style="text-align: center">
                <input type="submit" class="btn btn-info" value="添加规则">
            </div>
        </form>
        <form class="navbar-form navbar-left" action="{% url 'dqc:search' %}">
            {% csrf_token %}
            <div class="form-group">
                <input value="{{ param_input }}" type="text" name="a" class="form-control" placeholder="Search">
                <input type="submit" class="btn btn-info" value="搜索">
            </div>
        </form>
        <div style="clear:both" > </div>
    </div>

    <table class="table table-bordered table-striped table-hover mb-none" id="datatable-editable">
        <style>
            th,td {text-align: center}
        </style>
        <tr>
            <th>规则id</th>
            <th>应用名称</th>
{#            <th>作业名称</th>#}
            <th>库名</th>
            <th>表名</th>
{#            <th>文件路径</th>#}
{#            <th>统计字段名</th>#}
            <th>报错预警</th>
{#            <th>出数时间预警:星期</th>#}
            <th>出数时间预警:小时</th>
            <th>责任人</th>
            <th>责任人手机号</th>
            <th>有效标识</th>
            <th>操作</th>
        </tr>

        {% for dqc in dqc_list %}
        <tr >

            <td class="active" >{{ dqc.id }}</td>
            <td class="success"> {{ dqc.app_name }}</td>
{#            <td>{{ dqc.job_name }}</td>#}
            <td class="info">{{ dqc.db_name }}</td>
            <td class="active">{{ dqc.table_name }}</td>
{#            <td>{{ dqc.file_dir }}</td>#}
{#            <td>{{ dqc.static_column }}</td>#}
            <td class="success">{{ dqc.error_alarm }}</td>
{#            <td>{{ dqc.date_week }}</td>#}
            <td class="info">{{ dqc.date_alarm }}</td>
            <td class="active">{{ dqc.owner }}</td>
            <td class="success">{{ dqc.mobile }}</td>
            <td class="info">{{ dqc.valid_flag }}</td>
            <td class="active" style="text-align: center">
                <a class="btn btn-info" href="{% url 'dqc:del' %}?nid={{ dqc.id }}">删除</a>
                <a class="btn btn-info" href="{% url 'dqc:edit' %}?nid={{ dqc.id }}">编辑</a>
            </td>

        </tr>
        {% endfor %}

        </table>
    <nav aria-label="Page navigation">
        <ul class="pagination">
            {% if dqc_list.has_previous %}
                <li>
                  <a href="?page={{ dqc_list.previous_page_number }}&a={{ param_input }}" aria-label="Previous">
                      <span aria-hidden="true">&laquo;</span>
                  </a>
                </li>
            {% endif %}

            {% for pg in dqc_list.paginator.page_range %}
                {% if pg.number == pg %}
                    <span class="current">{{ pg }}</span>
                {% else %}
                    <li><a href="?page={{ pg }}&a={{ param_input }}">{{ pg }}</a></li>
                {% endif %}
            {% endfor %}

            {% if dqc_list.has_next %}
                <li>
                    <a href="?page={{ dqc_list.next_page_number }}&a={{ param_input }}" aria-label="Previous">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            {% endif %}
        </ul>
    </nav>
</div>
{% endblock content %}

templates/login.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en" class="no-js">

    <head>

        <meta charset="utf-8">
        <title>Fullscreen Login</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">

        <!-- CSS -->
        <link rel='stylesheet' href='http://fonts.googleapis.com/css?family=PT+Sans:400,700'>
        <link rel="stylesheet" href="{% static 'login/css/reset.css' %}">
        <link rel="stylesheet" href="{% static 'login/css/supersized.css' %}">
        <link rel="stylesheet" href="{% static 'login/css/style.css' %}">

        <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
        <!--[if lt IE 9]>
            <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->

    </head>

    <body>

        <div class="page-container">
            <h1 style="font-family: '微软雅黑 Light'">Data Management System</h1>
            <form action="{% url 'dqc:login' %}" method="post" class="navbar-form">
                {% csrf_token %}
                <input type="text" name="username" style="font-family: '微软雅黑 Light'" placeholder="Username">
                <input type="password" name="password" style="font-family: '微软雅黑 Light'" placeholder="Password">
                <div class="form-group">
                    <button type="submit" name = "login" class="btn btn-info" style="background: #00D9D9;border-color: #00D9D9;font-family: '微软雅黑 Light'">登录</button>
                    <button type="submit" name = "register" class="btn btn-info" style="background: #00D9D9;border-color: #00D9D9;font-family: '微软雅黑 Light'">注册</button>
                </div>
                <br>
                <h2 style="font-family: '微软雅黑 Light'">{{ login_check }}</h2>
            </form>
        </div>


        <!-- Javascript -->
        <script src="{% static 'login/js/jquery-1.8.2.min.js' %}"></script>
        <script src="{% static 'login/js/supersized.3.2.7.min.js' %}"></script>
        <script src="{% static 'login/js/supersized-init.js' %}"></script>
{#        <script src="{% static 'login/js/scripts.js' %}"></script>#}

    </body>

</html>